@startuml
hide empty description
state READY#LightBlue
state ALIGN#LightBlue
state SPIN#LightBlue
state STARTUP#LightBlue
state SPIN#LightBlue
state FREEWHEEL#LightBlue

state ReadyAlign #LightGrey
state AlignReady #LightGrey
state AlignStartup #LightGrey
state StartupSpin #LightGrey
state StartupFreewheel #LightGrey

state SpinFreewheel #LightGrey

state FreewheelReady #LightGrey

[*] -> READY : SET
READY --> ReadyAlign : speed_cmd != 0 <<transition>>
ReadyAlign -> ALIGN 
ALIGN --> AlignReady <<transition>>
AlignReady -> READY : speed_cmd == 0
ALIGN --> AlignStartup : aligned <<transition>>
AlignStartup --> STARTUP 
STARTUP -> StartupSpin : startup_ok <<transition>>
STARTUP -> StartupFreewheel : startup_fail <<transition>>
StartupSpin -> SPIN
StartupFreewheel -> FREEWHEEL
SPIN --> SpinFreewheel : speed_cmd == 0 <<transition>>
SpinFreewheel --> FREEWHEEL
FREEWHEEL --> FreewheelReady : speed_cmd == 0 <<transition>>
@enduml