/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.42.0.0
 *
 * Project: 'cmt_async_v1' 
 * Target:  'Target_1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32f10x.h"

/* Keil::CMSIS Driver:USART@2.3 */
#define RTE_Drivers_USART1              /* Driver USART1 */
#define RTE_Drivers_USART2              /* Driver USART2 */
#define RTE_Drivers_USART3              /* Driver USART3 */
#define RTE_Drivers_USART4              /* Driver UART4  */
#define RTE_Drivers_USART5              /* Driver UART5  */


#endif /* RTE_COMPONENTS_H */
